export type PODConnectionType = 'high-voltage' | 'low-voltage';
export type PODStatus = 'active' | 'inactive';
export type MaintenanceStatus = 'scheduled' | 'completed' | 'urgent' | 'none';
export type BillingStatus = 'up-to-date' | 'overdue' | 'pending';
export type BillingCycle = 'monthly' | 'quarterly' | 'annually';
export type MeteringType = 'manual' | 'smart';

export interface POD {
  id: string;
  name: string;
  consumer_id: string;
  connection_type: PODConnectionType;
  status: PODStatus;
  installed_capacity: number;
  location: string;
  current_consumption: number;
  peak_demand: number;
  daily_usage: number;
  monthly_usage: number;
  annual_usage: number;
  tariff_plan: string | null;
  last_maintenance: string | null;
  created_at: string | null;
  updated_at: string | null;
  street_address: string | null;
  city: string | null;
  state: string | null;
  postal_code: string | null;
  country: string | null;
  latitude: number | null;
  longitude: number | null;
  energy_type: string | null;
  power_factor: number | null;
  meter_id: string | null;
  smart_meter_id: string | null;
  last_meter_reading: number;
  last_meter_reading_date: string | null;
  metering_type: MeteringType | null;
  activation_date: string | null;
  deactivation_date: string | null;
  maintenance_status: MaintenanceStatus;
  maintenance_notes: string | null;
  energy_source: string | null;
  renewable_percentage: number;
  voltage_stability: number | null;
  frequency_deviation: number | null;
  billing_status: BillingStatus;
  billing_cycle: BillingCycle;
  outstanding_charges: number;
}