"""update_configuration_schema

Revision ID: 773750982ec2
Revises: 01_create_cer_configuration
Create Date: 2025-02-07 08:22:38.688645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '773750982ec2'
down_revision: Union[str, None] = '01_create_cer_configuration'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cer_configuration', sa.Column('gse_compliance', sa.JSON(), server_default='{}', nullable=False))
    op.alter_column('cer_configuration', 'simulation_settings',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::json"))
    op.alter_column('cer_configuration', 'billing_settings',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::json"))
    op.drop_column('cer_configuration', 'restrictions')
    op.drop_column('cer_configuration', 'energy_source')
    op.drop_column('cer_configuration', 'features')
    op.drop_column('cer_configuration', 'version')
    op.drop_column('cer_configuration', 'capacity')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cer_configuration', sa.Column('capacity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('cer_configuration', sa.Column('version', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('cer_configuration', sa.Column('features', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'{}'::json"), autoincrement=False, nullable=False))
    op.add_column('cer_configuration', sa.Column('energy_source', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('cer_configuration', sa.Column('restrictions', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'{}'::json"), autoincrement=False, nullable=False))
    op.alter_column('cer_configuration', 'billing_settings',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::json"))
    op.alter_column('cer_configuration', 'simulation_settings',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::json"))
    op.drop_column('cer_configuration', 'gse_compliance')
    # ### end Alembic commands ###
